{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_banner",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lib_banner-0.0.1.aar",
          "url": "lib_banner-0.0.1.aar",
          "size": 45411,
          "sha512": "f6e2113a3d53a597cb4ff94cada263ae39bd1278006dbc85d8daf9c3f486bbed870de214b201f75edd518c7189a6a1b1eeb856ce64a421309aa67024324e4ffd",
          "sha256": "347facb4df503ea27f7cec72bdc1b81a4ff34a9fa0418a73915bbbae00d1b2f8",
          "sha1": "e211e2922ba13ef922ecae80c2d32894f3acd050",
          "md5": "641515aad0a9af18da272705c9f633ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "latest.release"
          }
        }
      ],
      "files": [
        {
          "name": "lib_banner-0.0.1.aar",
          "url": "lib_banner-0.0.1.aar",
          "size": 45411,
          "sha512": "f6e2113a3d53a597cb4ff94cada263ae39bd1278006dbc85d8daf9c3f486bbed870de214b201f75edd518c7189a6a1b1eeb856ce64a421309aa67024324e4ffd",
          "sha256": "347facb4df503ea27f7cec72bdc1b81a4ff34a9fa0418a73915bbbae00d1b2f8",
          "sha1": "e211e2922ba13ef922ecae80c2d32894f3acd050",
          "md5": "641515aad0a9af18da272705c9f633ac"
        }
      ]
    }
  ]
}
