{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_banner",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lib_banner-0.0.1.aar",
          "url": "lib_banner-0.0.1.aar",
          "size": 45411,
          "sha512": "52036dd0a04cadf081eacfd709c3d48de7b294bb8c7a60bb1b82c88f76c536442b838b233cfb0f279af4f0b74c4ac2968c43e2b1d15b73a1202f9bc87806aba1",
          "sha256": "0bf72702bf9c92f0d3f1b49183a82a92e9a3487378acd4d8c682bab667d8179a",
          "sha1": "281d61c95c0101756aed558c86e98a78b2fcb194",
          "md5": "766a2c46c852a0111f290c31a1fcc7f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "latest.release"
          }
        }
      ],
      "files": [
        {
          "name": "lib_banner-0.0.1.aar",
          "url": "lib_banner-0.0.1.aar",
          "size": 45411,
          "sha512": "52036dd0a04cadf081eacfd709c3d48de7b294bb8c7a60bb1b82c88f76c536442b838b233cfb0f279af4f0b74c4ac2968c43e2b1d15b73a1202f9bc87806aba1",
          "sha256": "0bf72702bf9c92f0d3f1b49183a82a92e9a3487378acd4d8c682bab667d8179a",
          "sha1": "281d61c95c0101756aed558c86e98a78b2fcb194",
          "md5": "766a2c46c852a0111f290c31a1fcc7f1"
        }
      ]
    }
  ]
}
