{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_mmkv",
    "version": "1.2.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "lib_mmkv-1.2.13.aar",
          "url": "lib_mmkv-1.2.13.aar",
          "size": 48921,
          "sha512": "b1ea9aadc955168ee085e83933dd31acf0c2220bded1a4099086e463c6f6a19e4873646010a893852bc638d20d0cff52b43458e375cdc0e290e2fd8bcf37b2d5",
          "sha256": "e28765930df7c185e12a34ff7f0b2869923e4f323fd7fc85aa2afc7b02f333a2",
          "sha1": "20c3d969c232c83491f7cae6a5fb4d1ff976d88b",
          "md5": "4ada146c6939ced1c05ed1915c17dc11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lib_mmkv-1.2.13.aar",
          "url": "lib_mmkv-1.2.13.aar",
          "size": 48921,
          "sha512": "b1ea9aadc955168ee085e83933dd31acf0c2220bded1a4099086e463c6f6a19e4873646010a893852bc638d20d0cff52b43458e375cdc0e290e2fd8bcf37b2d5",
          "sha256": "e28765930df7c185e12a34ff7f0b2869923e4f323fd7fc85aa2afc7b02f333a2",
          "sha1": "20c3d969c232c83491f7cae6a5fb4d1ff976d88b",
          "md5": "4ada146c6939ced1c05ed1915c17dc11"
        }
      ]
    }
  ]
}
