{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_brv",
    "version": "1.3.75",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.xihan",
          "module": "lib_statelayout",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-layout-kernel",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-header-material",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-footer-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_brv-1.3.75.aar",
          "url": "lib_brv-1.3.75.aar",
          "size": 137071,
          "sha512": "121b5221e0b7fb3211ee3ad2810f290ed6fa8345821e6b52bd83028176ced811bc0cc6c453fe183905d4708c8b81f60299f1ea454aae82c67f3bc4f35c6accf3",
          "sha256": "0f9ab6e354ca97f6faf6cae62cfc4506f8bfb8a4622b59f79e89d39cdaebf24b",
          "sha1": "54d885b3127b76017d4e3b286a9785c3b0018ab4",
          "md5": "fd284dfb42fd28bdee13961cb2674fbc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.xihan",
          "module": "lib_statelayout",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-layout-kernel",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-header-material",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-footer-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lib_brv-1.3.75.aar",
          "url": "lib_brv-1.3.75.aar",
          "size": 137071,
          "sha512": "121b5221e0b7fb3211ee3ad2810f290ed6fa8345821e6b52bd83028176ced811bc0cc6c453fe183905d4708c8b81f60299f1ea454aae82c67f3bc4f35c6accf3",
          "sha256": "0f9ab6e354ca97f6faf6cae62cfc4506f8bfb8a4622b59f79e89d39cdaebf24b",
          "sha1": "54d885b3127b76017d4e3b286a9785c3b0018ab4",
          "md5": "fd284dfb42fd28bdee13961cb2674fbc"
        }
      ]
    }
  ]
}
