{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_brv",
    "version": "1.3.75",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.xihan",
          "module": "lib_statelayout",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-layout-kernel",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-header-material",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-footer-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "lib_brv-1.3.75.aar",
          "url": "lib_brv-1.3.75.aar",
          "size": 138522,
          "sha512": "42dd095048e2ef52c8fe552d80414f862a8c039c9c6040713b0f0220d21b8f19172df5bdde77ce17d344bcedff81ca62540e9d7169afd764afb121449a3ed1e7",
          "sha256": "25b1b66c3b6d5384e18b326df87fa029f2935d206288cf82236c9b22ed580e50",
          "sha1": "9e33e8a3e8a84a1da8949f4c8b7b07e4f97a9483",
          "md5": "2df4ffc22b10fdf226375e080c949493"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.xihan",
          "module": "lib_statelayout",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-layout-kernel",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-header-material",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-footer-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lib_brv-1.3.75.aar",
          "url": "lib_brv-1.3.75.aar",
          "size": 138522,
          "sha512": "42dd095048e2ef52c8fe552d80414f862a8c039c9c6040713b0f0220d21b8f19172df5bdde77ce17d344bcedff81ca62540e9d7169afd764afb121449a3ed1e7",
          "sha256": "25b1b66c3b6d5384e18b326df87fa029f2935d206288cf82236c9b22ed580e50",
          "sha1": "9e33e8a3e8a84a1da8949f4c8b7b07e4f97a9483",
          "md5": "2df4ffc22b10fdf226375e080c949493"
        }
      ]
    }
  ]
}
