{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_extensions",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "lib_extensions-0.0.1.aar",
          "url": "lib_extensions-0.0.1.aar",
          "size": 100333,
          "sha512": "f0fec607a69591bf8f2733efb2248f6f8fefe8f010292012f43ae48f71d036001e51653dbf957aa8400236b315f032024d114c1dcac01ee989116db3f39906af",
          "sha256": "f8c510cd88ad713743448ea4da486731a3815262889de635e10663ac2158bdc1",
          "sha1": "944b67b2b989904908edcbd4f4d5a35a3889dfe5",
          "md5": "e759b25d794802c5d56ac79a1cf50c3f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib_extensions-0.0.1.aar",
          "url": "lib_extensions-0.0.1.aar",
          "size": 100333,
          "sha512": "f0fec607a69591bf8f2733efb2248f6f8fefe8f010292012f43ae48f71d036001e51653dbf957aa8400236b315f032024d114c1dcac01ee989116db3f39906af",
          "sha256": "f8c510cd88ad713743448ea4da486731a3815262889de635e10663ac2158bdc1",
          "sha1": "944b67b2b989904908edcbd4f4d5a35a3889dfe5",
          "md5": "e759b25d794802c5d56ac79a1cf50c3f"
        }
      ]
    }
  ]
}
