{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_spannable",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_spannable-1.1.4.aar",
          "url": "lib_spannable-1.1.4.aar",
          "size": 19919,
          "sha512": "0c428891617fc4a02666aa0a86cfa73ea3027543ca515a036c077cfdb0e193da42bea6d172774e363e044e748d05655cf891c244c098cbeaf2d8a0d98725c196",
          "sha256": "25a839c73f25002abf5beb561121d4c567b1f34ec2cf7459f18d61602c7d0bfe",
          "sha1": "071c7fd71d42b58e562117e378cb9cc940ea838b",
          "md5": "d5d0815c734f72b02c5df0386bb8c916"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lib_spannable-1.1.4.aar",
          "url": "lib_spannable-1.1.4.aar",
          "size": 19919,
          "sha512": "0c428891617fc4a02666aa0a86cfa73ea3027543ca515a036c077cfdb0e193da42bea6d172774e363e044e748d05655cf891c244c098cbeaf2d8a0d98725c196",
          "sha256": "25a839c73f25002abf5beb561121d4c567b1f34ec2cf7459f18d61602c7d0bfe",
          "sha1": "071c7fd71d42b58e562117e378cb9cc940ea838b",
          "md5": "d5d0815c734f72b02c5df0386bb8c916"
        }
      ]
    }
  ]
}
