{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_spannable",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_spannable-1.1.4.aar",
          "url": "lib_spannable-1.1.4.aar",
          "size": 22984,
          "sha512": "90ad56b5b40a4eaeeac883db63bba3ef6965bdad846461be7fd020f2c17caa21dffd4dacd6ab7183f657f801db5a70ed3fe6a56069f9d85628e5368820739666",
          "sha256": "c575755bd5e569e9b7eeb89879df204aa119107c38b72ee7799b4af93ba2926d",
          "sha1": "96b09c1fcface0dc47dbafeeda8574dbc5e25448",
          "md5": "c6b06c70f2e4f643adb43e92e9074cf2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_spannable-1.1.4.aar",
          "url": "lib_spannable-1.1.4.aar",
          "size": 22984,
          "sha512": "90ad56b5b40a4eaeeac883db63bba3ef6965bdad846461be7fd020f2c17caa21dffd4dacd6ab7183f657f801db5a70ed3fe6a56069f9d85628e5368820739666",
          "sha256": "c575755bd5e569e9b7eeb89879df204aa119107c38b72ee7799b4af93ba2926d",
          "sha1": "96b09c1fcface0dc47dbafeeda8574dbc5e25448",
          "md5": "c6b06c70f2e4f643adb43e92e9074cf2"
        }
      ]
    }
  ]
}
