{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_sniffing",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib_sniffing-0.0.1.aar",
          "url": "lib_sniffing-0.0.1.aar",
          "size": 32756,
          "sha512": "4d49b097825ccb9b1c4aa00fcb5df4639c08d34bf293470404fe99d5a28b69773d59c9ec60d688eb68c3d9f487c5801fa02a676554316a213fd300241eb3dd8e",
          "sha256": "4fa2b60f260157c5e04d4559009af6f8ec300a3f150b19ecd797aa7cd20b3200",
          "sha1": "1ee77f7ec9957c3640dede3285f26a7d32b6aafc",
          "md5": "aac28ee325457a195849c762d4b84e86"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib_sniffing-0.0.1.aar",
          "url": "lib_sniffing-0.0.1.aar",
          "size": 32756,
          "sha512": "4d49b097825ccb9b1c4aa00fcb5df4639c08d34bf293470404fe99d5a28b69773d59c9ec60d688eb68c3d9f487c5801fa02a676554316a213fd300241eb3dd8e",
          "sha256": "4fa2b60f260157c5e04d4559009af6f8ec300a3f150b19ecd797aa7cd20b3200",
          "sha1": "1ee77f7ec9957c3640dede3285f26a7d32b6aafc",
          "md5": "aac28ee325457a195849c762d4b84e86"
        }
      ]
    }
  ]
}
