{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_sniffing",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "lib_sniffing-0.0.1.aar",
          "url": "lib_sniffing-0.0.1.aar",
          "size": 32691,
          "sha512": "487f274a5fad94c85006f4e5e67eeb6d4539d7563499267edd4f939d3781be75bc20b5f089b62980861208b6c53b29c688888ff5016efd8b37bb496a2a94a3e2",
          "sha256": "95258c08f8ea84cd58cb681fa2127e803e7d42cde925e4c17264f26bf674ede6",
          "sha1": "94a91990744ac3bd8d92b7464010a292248a85af",
          "md5": "5da3328024815b4f059b1fa9406f0c4a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha05"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.2"
          }
        }
      ],
      "files": [
        {
          "name": "lib_sniffing-0.0.1.aar",
          "url": "lib_sniffing-0.0.1.aar",
          "size": 32691,
          "sha512": "487f274a5fad94c85006f4e5e67eeb6d4539d7563499267edd4f939d3781be75bc20b5f089b62980861208b6c53b29c688888ff5016efd8b37bb496a2a94a3e2",
          "sha256": "95258c08f8ea84cd58cb681fa2127e803e7d42cde925e4c17264f26bf674ede6",
          "sha1": "94a91990744ac3bd8d92b7464010a292248a85af",
          "md5": "5da3328024815b4f059b1fa9406f0c4a"
        }
      ]
    }
  ]
}
