{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_sniffing",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib_sniffing-0.0.1.aar",
          "url": "lib_sniffing-0.0.1.aar",
          "size": 33033,
          "sha512": "d1bef2fdfd0ab0cd8fa0270657e807d93420f6ac4557d069e69bee2f4c144bf79d7ccae7f6d8583e2e7b3bc7208aadc3653cc1542c6fd38ddaeb18c0fe8aa49c",
          "sha256": "2746a5f3b5c488c05090b0464be6a0104b2e7d7e0d51c15814c7516065e301df",
          "sha1": "9c1a62ad82d0f21a4475c56d71cea8c05fec96f7",
          "md5": "0f4d7c45d99e168daa7089a713cb467b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.15.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib_sniffing-0.0.1.aar",
          "url": "lib_sniffing-0.0.1.aar",
          "size": 33033,
          "sha512": "d1bef2fdfd0ab0cd8fa0270657e807d93420f6ac4557d069e69bee2f4c144bf79d7ccae7f6d8583e2e7b3bc7208aadc3653cc1542c6fd38ddaeb18c0fe8aa49c",
          "sha256": "2746a5f3b5c488c05090b0464be6a0104b2e7d7e0d51c15814c7516065e301df",
          "sha1": "9c1a62ad82d0f21a4475c56d71cea8c05fec96f7",
          "md5": "0f4d7c45d99e168daa7089a713cb467b"
        }
      ]
    }
  ]
}
