{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_brv",
    "version": "1.3.79",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.xihan",
          "module": "lib_statelayout",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-layout-kernel",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-header-material",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-footer-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.0-alpha07"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.0-alpha07"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.0-alpha07"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_brv-1.3.79.aar",
          "url": "lib_brv-1.3.79.aar",
          "size": 137740,
          "sha512": "bbfd55221b2f4ac0862bf90d08b25843bf96c33d9f298dab038e5fdb871507264a980e8e0fe3d661aa6b7c4cb677fe70744e569072be6fb569ed1169dbfa79f7",
          "sha256": "248ed439612e0ad4df2e0e3d1a97d67ed35669943eb1d34b47e6f13c652df25c",
          "sha1": "ac4a5387e47398f2e0de2b6737c9a0a7d494a96d",
          "md5": "0098646c4414a69f46bd6fd7f544bf3a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.xihan",
          "module": "lib_statelayout",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-layout-kernel",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-header-material",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-footer-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.0-alpha07"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.0-alpha07"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.0-alpha07"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "lib_brv-1.3.79.aar",
          "url": "lib_brv-1.3.79.aar",
          "size": 137740,
          "sha512": "bbfd55221b2f4ac0862bf90d08b25843bf96c33d9f298dab038e5fdb871507264a980e8e0fe3d661aa6b7c4cb677fe70744e569072be6fb569ed1169dbfa79f7",
          "sha256": "248ed439612e0ad4df2e0e3d1a97d67ed35669943eb1d34b47e6f13c652df25c",
          "sha1": "ac4a5387e47398f2e0de2b6737c9a0a7d494a96d",
          "md5": "0098646c4414a69f46bd6fd7f544bf3a"
        }
      ]
    }
  ]
}
