{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_whatif",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_whatif-1.1.1.aar",
          "url": "lib_whatif-1.1.1.aar",
          "size": 19451,
          "sha512": "5d865b3e7e6dff8b0149715d7e7e183fba9135bc6b7f00265e6ebd2ffea253e08b7c826b8ac87c45f45f22a79121caf2829f91566fdf7a4f0e68d92c39f1c342",
          "sha256": "dfe7eaef5c78fe5cadcd61915dcccc3ee1d9540d59f38d81ed8af83c815151b7",
          "sha1": "6ddc9dff3e146569252ae27560f43cd9f3920cab",
          "md5": "8981bb92e5f9b09fd1fa1337454171b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_whatif-1.1.1.aar",
          "url": "lib_whatif-1.1.1.aar",
          "size": 19451,
          "sha512": "5d865b3e7e6dff8b0149715d7e7e183fba9135bc6b7f00265e6ebd2ffea253e08b7c826b8ac87c45f45f22a79121caf2829f91566fdf7a4f0e68d92c39f1c342",
          "sha256": "dfe7eaef5c78fe5cadcd61915dcccc3ee1d9540d59f38d81ed8af83c815151b7",
          "sha1": "6ddc9dff3e146569252ae27560f43cd9f3920cab",
          "md5": "8981bb92e5f9b09fd1fa1337454171b3"
        }
      ]
    }
  ]
}
