{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_whatif",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_whatif-1.1.1.aar",
          "url": "lib_whatif-1.1.1.aar",
          "size": 19451,
          "sha512": "5299a7762603ef4350f5c880045789ec81622c8414d9fe98d26482c63f67af66d255eece639e7b1043696b777a00cac1b28bc7afba7795c8ba83f9599ecbc33f",
          "sha256": "63d8904ad18b1164239423873ff2e5d31e4c1921a967573331ed778c83547479",
          "sha1": "587bf83999912b26b59dfd330e368e591cc18b9b",
          "md5": "a609ce62fe61f9af94e1b7909398a70b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_whatif-1.1.1.aar",
          "url": "lib_whatif-1.1.1.aar",
          "size": 19451,
          "sha512": "5299a7762603ef4350f5c880045789ec81622c8414d9fe98d26482c63f67af66d255eece639e7b1043696b777a00cac1b28bc7afba7795c8ba83f9599ecbc33f",
          "sha256": "63d8904ad18b1164239423873ff2e5d31e4c1921a967573331ed778c83547479",
          "sha1": "587bf83999912b26b59dfd330e368e591cc18b9b",
          "md5": "a609ce62fe61f9af94e1b7909398a70b"
        }
      ]
    }
  ]
}
