{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_whatif",
    "version": "1.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "lib_whatif-1.1.1.aar",
          "url": "lib_whatif-1.1.1.aar",
          "size": 19444,
          "sha512": "f154b910c98a29d9b77d686df4c86180192cadb014029a5fd52cb0ace1e8f024e2dc738aa106def6693a347b44a8f13690f76f03934d874fe21d01c3bc6e3644",
          "sha256": "b4c0be0420877360fc8e937cde0fea21456d0c02ac62ce17d15de49b52593893",
          "sha1": "428aac8acce358268c26208bf73703ae3fd0056b",
          "md5": "e95317f70a0bbfbac94b4b978dcf3fdc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.7.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "lib_whatif-1.1.1.aar",
          "url": "lib_whatif-1.1.1.aar",
          "size": 19444,
          "sha512": "f154b910c98a29d9b77d686df4c86180192cadb014029a5fd52cb0ace1e8f024e2dc738aa106def6693a347b44a8f13690f76f03934d874fe21d01c3bc6e3644",
          "sha256": "b4c0be0420877360fc8e937cde0fea21456d0c02ac62ce17d15de49b52593893",
          "sha1": "428aac8acce358268c26208bf73703ae3fd0056b",
          "md5": "e95317f70a0bbfbac94b4b978dcf3fdc"
        }
      ]
    }
  ]
}
