{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_JZVideo",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_JZVideo-0.0.3.aar",
          "url": "lib_JZVideo-0.0.3.aar",
          "size": 78431,
          "sha512": "cd3cfb5a7eb670e3d3c0a719ec8ad9f8ef0819f6d70f039ed21aa7535ea535ea92c7416cb52cc07782e70a0be5d53f5e0888a53d2cbc5bd27ac606dd05f04334",
          "sha256": "6a1990e496df75687b2e6657e74f68094a41a73a6fab956fc7bdf6274532478c",
          "sha1": "e40a99de98cab272cf8e9213e4f45c4cace6893c",
          "md5": "9425f3be5d18952f69ca185512c12cd4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_JZVideo-0.0.3.aar",
          "url": "lib_JZVideo-0.0.3.aar",
          "size": 78431,
          "sha512": "cd3cfb5a7eb670e3d3c0a719ec8ad9f8ef0819f6d70f039ed21aa7535ea535ea92c7416cb52cc07782e70a0be5d53f5e0888a53d2cbc5bd27ac606dd05f04334",
          "sha256": "6a1990e496df75687b2e6657e74f68094a41a73a6fab956fc7bdf6274532478c",
          "sha1": "e40a99de98cab272cf8e9213e4f45c4cace6893c",
          "md5": "9425f3be5d18952f69ca185512c12cd4"
        }
      ]
    }
  ]
}
