{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_statelayout",
    "version": "1.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_statelayout-1.3.8.aar",
          "url": "lib_statelayout-1.3.8.aar",
          "size": 29608,
          "sha512": "d8053cfce7d87caa98a104944511d55d4f10943cfd9044db8bcefa7cae3af8db967563e74785447068ade1e2f1896c40fec5f64b596b2b7aeecbaca0c115ad46",
          "sha256": "95194015008641bcc4203f2a29fb79bb157dfcb4e27358c178911508afdc0378",
          "sha1": "3bf3877a02a6057778008450201196bccaf791da",
          "md5": "4ae703db2043ab3ef5f7fd258f9f2ffa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "lib_statelayout-1.3.8.aar",
          "url": "lib_statelayout-1.3.8.aar",
          "size": 29608,
          "sha512": "d8053cfce7d87caa98a104944511d55d4f10943cfd9044db8bcefa7cae3af8db967563e74785447068ade1e2f1896c40fec5f64b596b2b7aeecbaca0c115ad46",
          "sha256": "95194015008641bcc4203f2a29fb79bb157dfcb4e27358c178911508afdc0378",
          "sha1": "3bf3877a02a6057778008450201196bccaf791da",
          "md5": "4ae703db2043ab3ef5f7fd258f9f2ffa"
        }
      ]
    }
  ]
}
