{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_statelayout",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "lib_statelayout-1.3.3.aar",
          "url": "lib_statelayout-1.3.3.aar",
          "size": 28783,
          "sha512": "3dca4d7ee1fb79f08640ae237a60cdf5e6609b4b61f399ae14ea69a0d980e524fc8965da108de99917e5032ef6377407d595c264595a26c74ccf039e30da9fc5",
          "sha256": "7616d9892bb75d3201877c5c1c4a8aef62e82ff6520f9ca67ee5cc8f62282d62",
          "sha1": "9286fbb707e3e758d7adde87ec6ac2c80f56629d",
          "md5": "b847651e0826ab2dfff6f1ef0f153c2a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.0-RC"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.0-alpha01"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lib_statelayout-1.3.3.aar",
          "url": "lib_statelayout-1.3.3.aar",
          "size": 28783,
          "sha512": "3dca4d7ee1fb79f08640ae237a60cdf5e6609b4b61f399ae14ea69a0d980e524fc8965da108de99917e5032ef6377407d595c264595a26c74ccf039e30da9fc5",
          "sha256": "7616d9892bb75d3201877c5c1c4a8aef62e82ff6520f9ca67ee5cc8f62282d62",
          "sha1": "9286fbb707e3e758d7adde87ec6ac2c80f56629d",
          "md5": "b847651e0826ab2dfff6f1ef0f153c2a"
        }
      ]
    }
  ]
}
