{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_statelayout",
    "version": "1.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_statelayout-1.3.6.aar",
          "url": "lib_statelayout-1.3.6.aar",
          "size": 29129,
          "sha512": "17ac1daf9d39b085515573c18bd1297b6c93a493a8307f0bd650adf2065cfff62fc25cc5b019dc6f95d4a2a2bf462641dc2ffa5a0f2e75473977a3331e926946",
          "sha256": "e56185639155f146cd6efd2538d274ad6d5ccc285788174bd251c3aeb35238ca",
          "sha1": "53cd3070b89b2c99ac270f4248d0c60d623767ae",
          "md5": "8b433b627bd73cdbec89cc3611d373b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0-alpha05"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.0-alpha02"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lib_statelayout-1.3.6.aar",
          "url": "lib_statelayout-1.3.6.aar",
          "size": 29129,
          "sha512": "17ac1daf9d39b085515573c18bd1297b6c93a493a8307f0bd650adf2065cfff62fc25cc5b019dc6f95d4a2a2bf462641dc2ffa5a0f2e75473977a3331e926946",
          "sha256": "e56185639155f146cd6efd2538d274ad6d5ccc285788174bd251c3aeb35238ca",
          "sha1": "53cd3070b89b2c99ac270f4248d0c60d623767ae",
          "md5": "8b433b627bd73cdbec89cc3611d373b4"
        }
      ]
    }
  ]
}
