{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_brv",
    "version": "1.3.77",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.xihan",
          "module": "lib_statelayout",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-layout-kernel",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-header-material",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-footer-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_brv-1.3.77.aar",
          "url": "lib_brv-1.3.77.aar",
          "size": 137374,
          "sha512": "5ceacccd5a78dc8a877b2363c41d030b052c785c16be8ec88bfddad18e9623b871608d02d2ccc33adf6d975663a3484ff118d973d8479de94124a2a3e393ef04",
          "sha256": "62b71191be73a2835763a450470474a59b1a3fa03fe6f92f6584ce942eaab7d3",
          "sha1": "f92d3fcfe0e0fd02424343619c9493534d53efbf",
          "md5": "7389c88436e56e33e790302108a02df9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.xihan",
          "module": "lib_statelayout",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-layout-kernel",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-header-material",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-footer-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lib_brv-1.3.77.aar",
          "url": "lib_brv-1.3.77.aar",
          "size": 137374,
          "sha512": "5ceacccd5a78dc8a877b2363c41d030b052c785c16be8ec88bfddad18e9623b871608d02d2ccc33adf6d975663a3484ff118d973d8479de94124a2a3e393ef04",
          "sha256": "62b71191be73a2835763a450470474a59b1a3fa03fe6f92f6584ce942eaab7d3",
          "sha1": "f92d3fcfe0e0fd02424343619c9493534d53efbf",
          "md5": "7389c88436e56e33e790302108a02df9"
        }
      ]
    }
  ]
}
