{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_statelayout",
    "version": "1.3.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_statelayout-1.3.5.aar",
          "url": "lib_statelayout-1.3.5.aar",
          "size": 29080,
          "sha512": "a282b0274ef442da1f8a7b09c100430792c49870fcc00e4a00254cdbb705a409e9a371021ee7e58d79a04e3671eb90be34ec91c5d833620c42f36eac129fdab0",
          "sha256": "f132de0e18669ebe77d2aa8288e86267c0590cb1aab7e40f5654ff221e1684cc",
          "sha1": "72817262ef12eec9c9c1f122ce29139fdac2c0e2",
          "md5": "0f79dc4f6863854ae0210b66fd797ace"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.0-alpha02"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lib_statelayout-1.3.5.aar",
          "url": "lib_statelayout-1.3.5.aar",
          "size": 29080,
          "sha512": "a282b0274ef442da1f8a7b09c100430792c49870fcc00e4a00254cdbb705a409e9a371021ee7e58d79a04e3671eb90be34ec91c5d833620c42f36eac129fdab0",
          "sha256": "f132de0e18669ebe77d2aa8288e86267c0590cb1aab7e40f5654ff221e1684cc",
          "sha1": "72817262ef12eec9c9c1f122ce29139fdac2c0e2",
          "md5": "0f79dc4f6863854ae0210b66fd797ace"
        }
      ]
    }
  ]
}
