{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_JZVideo",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_JZVideo-0.0.2.aar",
          "url": "lib_JZVideo-0.0.2.aar",
          "size": 77596,
          "sha512": "91213a0b3c7a844edc7eaf35323cd3b647f5b9c500ab63dad961c2a97a1422e4b1ec249a5c2b53834738e5f94df4e1dd822c9566dddb8b02a7fda3276c205b2b",
          "sha256": "2e0be257b4c9c8e85cb4ee7576a26e881efed15b23dba235ba6204426205049b",
          "sha1": "48524793c90660b7a2d2fa7213011b7c5610c955",
          "md5": "47ab210c071b799001d6b9cf8d820e11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_JZVideo-0.0.2.aar",
          "url": "lib_JZVideo-0.0.2.aar",
          "size": 77596,
          "sha512": "91213a0b3c7a844edc7eaf35323cd3b647f5b9c500ab63dad961c2a97a1422e4b1ec249a5c2b53834738e5f94df4e1dd822c9566dddb8b02a7fda3276c205b2b",
          "sha256": "2e0be257b4c9c8e85cb4ee7576a26e881efed15b23dba235ba6204426205049b",
          "sha1": "48524793c90660b7a2d2fa7213011b7c5610c955",
          "md5": "47ab210c071b799001d6b9cf8d820e11"
        }
      ]
    }
  ]
}
