{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_brv",
    "version": "1.3.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "cn.xihan",
          "module": "lib_statelayout",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-layout-kernel",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-header-material",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-footer-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.0-alpha02"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.0-alpha02"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.0-alpha02"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "lib_brv-1.3.71.aar",
          "url": "lib_brv-1.3.71.aar",
          "size": 138590,
          "sha512": "2257361ce5092103c01e58cbd3e1f0a5cb125cd2ecf274229b52334854cc62caf113b4899ba5778db0006bde46af7b06335a52197a4fd130d364ad74158be403",
          "sha256": "fbe5ef9d6c2030659b43aad217f065c961d6200b1871503b598754c8e6cdb206",
          "sha1": "d96d6ca337230a4216446a9dd174ed0d3b6a1581",
          "md5": "010b1e065c574e996a53368b800652e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.xihan",
          "module": "lib_statelayout",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-layout-kernel",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-header-material",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.github.scwang90",
          "module": "refresh-footer-classics",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.0-alpha02"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.0-alpha02"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.0-alpha02"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lib_brv-1.3.71.aar",
          "url": "lib_brv-1.3.71.aar",
          "size": 138590,
          "sha512": "2257361ce5092103c01e58cbd3e1f0a5cb125cd2ecf274229b52334854cc62caf113b4899ba5778db0006bde46af7b06335a52197a4fd130d364ad74158be403",
          "sha256": "fbe5ef9d6c2030659b43aad217f065c961d6200b1871503b598754c8e6cdb206",
          "sha1": "d96d6ca337230a4216446a9dd174ed0d3b6a1581",
          "md5": "010b1e065c574e996a53368b800652e4"
        }
      ]
    }
  ]
}
