{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_JZVideo",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_JZVideo-0.0.1.aar",
          "url": "lib_JZVideo-0.0.1.aar",
          "size": 80824,
          "sha512": "0e3c7fbf3c32a0e7aedf551cfe7de25a98598b9e73e8675c7c0060eb7c2c19a88c895ed356179fac9b35cf0fd1430c52f03925425284e0f16a43f91d66abc8fb",
          "sha256": "5e5d132f99de7ed87d0ed1faa4a4a6089100194c0dc187ae7debd424839348fc",
          "sha1": "9a9ee1a8e10d06d7b9afd07d922dc89ce16b6f94",
          "md5": "456b6ede56386c689a1adb5f1bc5ee9f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "lib_JZVideo-0.0.1.aar",
          "url": "lib_JZVideo-0.0.1.aar",
          "size": 80824,
          "sha512": "0e3c7fbf3c32a0e7aedf551cfe7de25a98598b9e73e8675c7c0060eb7c2c19a88c895ed356179fac9b35cf0fd1430c52f03925425284e0f16a43f91d66abc8fb",
          "sha256": "5e5d132f99de7ed87d0ed1faa4a4a6089100194c0dc187ae7debd424839348fc",
          "sha1": "9a9ee1a8e10d06d7b9afd07d922dc89ce16b6f94",
          "md5": "456b6ede56386c689a1adb5f1bc5ee9f"
        }
      ]
    }
  ]
}
