{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_common",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "com.github.skydoves",
          "module": "bindables",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "lib_common-0.0.1.aar",
          "url": "lib_common-0.0.1.aar",
          "size": 46986,
          "sha512": "f27bf51c2aa16224e7f7392f32377ef60145fd45a2701f5b6cf291f9114d048395505d60645c6afd6650c99623eba1856716ed4be0c040176b0b88d9e1fb0b4a",
          "sha256": "82f83a54302c5f615f327794616f8642babf5e2c6e87c90b0f2d923b8a250eaa",
          "sha1": "4481abe4a9434a7cfe6646f18e88facae9e3d2c2",
          "md5": "178505e774ac82b7f8446042da638572"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.0-rc01"
          }
        },
        {
          "group": "com.github.skydoves",
          "module": "bindables",
          "version": {
            "requires": "1.0.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0-RC"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "lib_common-0.0.1.aar",
          "url": "lib_common-0.0.1.aar",
          "size": 46986,
          "sha512": "f27bf51c2aa16224e7f7392f32377ef60145fd45a2701f5b6cf291f9114d048395505d60645c6afd6650c99623eba1856716ed4be0c040176b0b88d9e1fb0b4a",
          "sha256": "82f83a54302c5f615f327794616f8642babf5e2c6e87c90b0f2d923b8a250eaa",
          "sha1": "4481abe4a9434a7cfe6646f18e88facae9e3d2c2",
          "md5": "178505e774ac82b7f8446042da638572"
        }
      ]
    }
  ]
}
