{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_mywidget",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_mywidget-0.0.1.aar",
          "url": "lib_mywidget-0.0.1.aar",
          "size": 84347,
          "sha512": "ff1ecfa9ef7dc8d2cc9bf8d10b4f52a1fe2648c9e944501b76d795871d4340663cf9df0a2ce3ba86816ce84f5071affd2237242b7c2c5d4324de967dd76e5d88",
          "sha256": "4c5da1aaa700313fa00c4960248223882dc1bedc034eee04a1decc44886d4103",
          "sha1": "c3db626600091f24536778f73cc2f98d487bfb15",
          "md5": "6b5f91f5259089e0a53c24906bb31d8b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_mywidget-0.0.1.aar",
          "url": "lib_mywidget-0.0.1.aar",
          "size": 84347,
          "sha512": "ff1ecfa9ef7dc8d2cc9bf8d10b4f52a1fe2648c9e944501b76d795871d4340663cf9df0a2ce3ba86816ce84f5071affd2237242b7c2c5d4324de967dd76e5d88",
          "sha256": "4c5da1aaa700313fa00c4960248223882dc1bedc034eee04a1decc44886d4103",
          "sha1": "c3db626600091f24536778f73cc2f98d487bfb15",
          "md5": "6b5f91f5259089e0a53c24906bb31d8b"
        }
      ]
    }
  ]
}
