{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.xihan",
    "module": "lib_mywidget",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_mywidget-0.0.1.aar",
          "url": "lib_mywidget-0.0.1.aar",
          "size": 84347,
          "sha512": "6336e1f8c1cbea14369f091601398b584426dfddb461ff5d1f987d7f59fc1d48ddab6096eca3558f247e3c3f17b0715302eb0fea2971b4b453ce461e93e37d5a",
          "sha256": "56c3a0f78b8fdcdde217f8d26e13ed4ef48b11ad006d43304a798aecca2b38ef",
          "sha1": "9998a774b02f0f7b91c311087d12089a99d48c23",
          "md5": "2823a4e4a02b2981f27ab23035f7df27"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "lib_mywidget-0.0.1.aar",
          "url": "lib_mywidget-0.0.1.aar",
          "size": 84347,
          "sha512": "6336e1f8c1cbea14369f091601398b584426dfddb461ff5d1f987d7f59fc1d48ddab6096eca3558f247e3c3f17b0715302eb0fea2971b4b453ce461e93e37d5a",
          "sha256": "56c3a0f78b8fdcdde217f8d26e13ed4ef48b11ad006d43304a798aecca2b38ef",
          "sha1": "9998a774b02f0f7b91c311087d12089a99d48c23",
          "md5": "2823a4e4a02b2981f27ab23035f7df27"
        }
      ]
    }
  ]
}
